import {api} from '../services/api.js';
import {heading,panel,icon,empty,esc,date} from '../components/ui.js';
export async function dashboard(){
 const d=await api('/dashboard'),c=d.counts;
 const cards=[['Total prospects',d.total,'prospects','','Every restaurant in your workspace'],['Qualified prospects',c.qualified,'check','qualified','Ready for a thoughtful introduction'],['Waiting for approval',c.awaiting_approval,'outreach','awaiting_approval','Initial messages need your review'],['Active free trials',c.free_trial,'clock','free_trial','30 days from account activation']];
 const actions=[['awaiting_approval','Review initial outreach','Approve or request a revised draft','outreach'],['followup_due','Follow-ups due','Scheduled automatically by the agent','prospects?filter=followup_due'],['strategy_ready','Strategies ready','Check notification and delivery','strategies'],['trial_ending','Trials ending soon','Five days or fewer remaining','prospects?filter=trial_ending'],['feedback_due','Feedback due','Check the end-of-trial conversation','prospects?filter=feedback_due'],['feedback_received','Feedback received','Read the restaurant experience','feedback'],['attention','Client issues','Review an issue requiring attention','feedback'],['analysis_failed','Analysis needs attention','Check the prospect and retry','prospects?filter=analysis_failed']].filter(([key])=>c[key]);
 const queue=actions.reduce((n,[key])=>n+c[key],0);
 return {html:heading('A clear view of what’s next.','Your prospects, conversations and client journeys — connected.',`<a class="button" href="#/prospects?add=1">+ Add prospect</a>`,'OVERVIEW')+
 (d.automation_enabled?'':'<div class="notice">Scheduled Strategy and follow-up processing is paused on this server. Draft review remains available.</div>')+
 `<section class="hero"><div><div class="eyebrow">RELATIONSHIPS, IN MOTION</div><h2>Make every introduction<br>the start of something good.</h2><p>${queue?`${queue} ${queue===1?'item':'items'} across your workspace need a look. Start with the action queue below.`:'Your action queue is clear. Explore your prospects to find the next opportunity.'}</p></div><div class="hero-art"><div><div class="big-number">${d.total}</div><small>prospects · one shared workspace</small></div><div class="orbit">✦</div></div></section>`+
 `<div class="stat-grid">${cards.map(([label,value,ic,f,note])=>`<a class="stat-card" href="#/${f==='awaiting_approval'?'outreach':'prospects'+(f?'?filter='+f:'')}"><div class="stat-top">${label}<span class="stat-icon">${icon(ic)}</span></div><div class="stat-value">${value}</div><div class="stat-note">${note}</div></a>`).join('')}</div>`+
 `<div class="two-col">${panel('Action required',actions.length?actions.map(([key,title,note,link])=>`<a class="action-row" href="#/${link}"><span class="count">${c[key]}</span><span><strong>${title}</strong><small>${note}</small></span><span class="arrow">${icon('arrow')}</span></a>`).join(''):empty('All caught up','New approvals, follow-ups and client issues will appear here.'),'<span class="count-label">Your next priorities</span>')}
 ${panel('The prospect journey',`<div class="panel-body">${Object.entries(d.stages).map(([label,n])=>`<div class="pipeline-row"><span>${esc(label)}</span><div class="bar"><i style="width:${d.total?n/d.total*100:0}%"></i></div><b>${n}</b></div>`).join('')}</div>`,'<a class="text-link" href="#/prospects">View prospects ↗</a>')}</div>`+
 `<div class="stat-grid">${[['Outreach sent',c.outreach_sent,'outreach'],['Waiting for response',c.waiting_response,'prospects?filter=waiting_response'],['Interested',c.interested,'prospects?filter=interested'],['Strategy in progress',c.strategy,'strategies'],['Active clients',c.active_client,'prospects?filter=active_client'],['Follow-ups due',c.followup_due,'prospects?filter=followup_due'],['Feedback due',c.feedback_due,'feedback'],['Issues to review',c.attention,'feedback']].map(([label,n,link])=>`<a class="stat-card" href="#/${link}"><div class="stat-top">${label}</div><div class="stat-value">${n}</div></a>`).join('')}</div>`,updated:d.updated_at};
}
