import {api,post} from '../services/api.js';
import {heading,panel,restaurant,badge,esc,date,human,icon,empty,modal,busy,toast,kv,lifecycle,trial} from '../components/ui.js';
const filters={all:'All prospects',qualified:'Qualified',awaiting_approval:'Awaiting approval',outreach_sent:'Outreach sent',waiting_response:'Waiting for response',interested:'Interested',strategy:'Strategy',active_client:'Active client',free_trial:'Free trial',feedback_due:'Feedback due',closed:'Closed',followup_due:'Follow-up due',trial_ending:'Trial ending soon',attention:'Needs attention',analysis_failed:'Analysis failed'};
export async function prospects(params){
 const {items,updated_at}=await api('/prospects');
 return {html:heading('Prospects','The right context for every relationship.',`<button class="button" id="add-prospect">+ Add prospect</button>`)+
 `<div class="toolbar"><div class="search">${icon('search')}<input id="search" aria-label="Search prospects" placeholder="Search restaurant, Instagram or email"></div><select id="filter" aria-label="Filter prospects">${Object.entries(filters).map(([key,label])=>`<option value="${key}" ${params.get('filter')===key?'selected':''}>${label}</option>`).join('')}</select><select id="sort" aria-label="Sort prospects"><option value="created_at">Recently added</option><option value="last_contact">Recently contacted</option><option value="next_contact">Follow-up due</option><option value="trial">Trial ending soon</option></select></div>`+
 `<section class="panel"><div class="panel-head"><h3>Restaurant directory</h3><span id="result-count" class="count-label"></span></div><div id="prospect-table"></div></section>`,updated:updated_at,
 bind(){const search=document.querySelector('#search'),filter=document.querySelector('#filter'),sort=document.querySelector('#sort');
 const render=()=>{let data=items.filter(p=>(filter.value==='all'||p.flags[filter.value])&&[p.name,p.instagram,p.email].some(x=>(x||'').toLowerCase().includes(search.value.toLowerCase())));
 data.sort((a,b)=>{const key=sort.value;if(key==='next_contact'||key==='trial'){const av=key==='trial'?a.trial?.end:a.next_contact,bv=key==='trial'?b.trial?.end:b.next_contact;return (av?Date.parse(av):Infinity)-(bv?Date.parse(bv):Infinity);}return Date.parse(b[key]||0)-Date.parse(a[key]||0);});
 document.querySelector('#result-count').textContent=`${data.length} of ${items.length} prospects`;
 document.querySelector('#prospect-table').innerHTML=data.length?`<div class="table-wrap"><table><thead><tr><th>Restaurant</th><th>Lifecycle</th><th>Status</th><th>Next action</th><th>Trial / timing</th><th></th></tr></thead><tbody>${data.map(p=>`<tr><td>${restaurant(p)}<span class="subline">${esc(p.email||'Email not added')}</span></td><td>${esc(p.stage)}<span class="mini-lifecycle" aria-label="Lifecycle progress">${p.lifecycle.map(step=>`<i class="${esc(step.state)}" title="${esc(step.label)}: ${esc(human(step.state))}"></i>`).join('')}</span></td><td>${badge(p.status)}</td><td>${esc(p.next_action)}<span class="subline">${p.location?esc(p.location):'Location not added'}</span></td><td>${p.trial?`${p.trial.days_remaining} days remaining<span class="subline">Ends ${date(p.trial.end)}</span>`:p.next_contact?`${date(p.next_contact)}<span class="subline">Next contact</span>`:'<span class="muted">—</span>'}</td><td><a class="text-link" href="#/prospects/${p.id}" aria-label="Open ${esc(p.name)}">${icon('arrow')}</a></td></tr>`).join('')}</tbody></table></div>`:empty(items.length?'No matching prospects':'Your next relationship starts here',items.length?'Try another search or filter.':'Add a restaurant to start research and qualification.');};
 search.oninput=render;filter.onchange=render;sort.onchange=render;render();document.querySelector('#add-prospect').onclick=()=>addProspect(items);if(params.get('add'))addProspect(items);}};
}
function addProspect(items){
 const d=modal(`<div class="modal-head"><div><div class="eyebrow">GROW YOUR WORKSPACE</div><h2>Add a prospect</h2></div><button class="icon-button" data-close aria-label="Close">×</button></div><p style="font-size:12px;margin-bottom:18px">Existing restaurants are already in your workspace. Find one below, or add a new restaurant.</p><input id="existing-search" placeholder="Find an existing restaurant" aria-label="Find existing restaurant"><div id="existing-results" style="max-height:145px;overflow:auto;margin-bottom:20px"></div><form id="add-form"><div class="form-grid"><div class="full"><label for="name">Restaurant name</label><input id="name" name="name" required maxlength="255"></div><div><label for="instagram">Instagram username</label><input id="instagram" name="instagram_username" required maxlength="30" placeholder="@restaurant"></div><div><label for="email">Contact email</label><input id="email" name="email" type="email" maxlength="255"></div><div class="full"><label for="location">Location</label><input id="location" name="location" maxlength="255" placeholder="City, area"></div></div><p id="form-error" role="alert"></p><div class="form-actions"><button type="button" class="button secondary" data-close>Cancel</button><button class="button" type="submit">Add prospect</button></div></form>`);
 const search=d.querySelector('#existing-search'),render=()=>{const value=search.value.toLowerCase();d.querySelector('#existing-results').innerHTML=items.filter(p=>[p.name,p.instagram,p.email].some(x=>(x||'').toLowerCase().includes(value))).slice(0,4).map(p=>`<a class="existing-result" href="#/prospects/${p.id}">${esc(p.name)}<small>@${esc(p.instagram)} · ${esc(p.stage)}</small></a>`).join('');d.querySelectorAll('.existing-result').forEach(a=>a.onclick=()=>d.close());};search.oninput=render;render();
 d.querySelector('#add-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;const values=Object.fromEntries(new FormData(e.target));for(const k of ['email','location'])if(!values[k])values[k]=null;try{const result=await post('/api/restaurants',values);d.close();location.hash=`#/prospects/${result.id}`;toast('Prospect added. You can now start analysis.');}catch(error){d.querySelector('#form-error').textContent=error.message;}finally{b.disabled=false;}};
}
export async function detail(id){
 const p=await api(`/prospects/${id}`);
 const link=(to,label)=>`<a class="text-link" href="#/${to}">${label} ↗</a>`;
 const research=p.research.date?`<div class="panel-body">${Object.entries(p.research.metrics).map(([k,v])=>kv(k,v)).join('')}<ul class="observations">${p.research.observations.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><small class="muted">Research completed ${date(p.research.date)}</small></div>`:empty('Research is not complete','Start the existing Research and Qualification workflow to build this prospect’s context.');
 const analyze=!p.flags.closed && ((!p.can_start && !p.qualification_run_id) || p.analysis_status==='failed');
 return {html:heading(p.name,`@${p.instagram} · ${p.email||'Email not added'}${p.location?' · '+p.location:''}`,`<a class="button secondary" href="#/prospects">← All prospects</a>`,'PROSPECT PROFILE')+
 (p.flags.closed?'<div class="notice">This restaurant has opted out. Promotional outreach is stopped.</div>':'')+
 panel('Relationship journey',lifecycle(p),badge(p.stage))+
 `<div class="detail-grid"><div>${panel('Restaurant & qualification',`<div class="panel-body">${kv('Restaurant',p.name)}${kv('Instagram','@'+p.instagram)}${kv('Email',p.email)}${kv('Location',p.location)}<div class="kv"><span>Qualification</span>${badge(p.qualification)}</div>${kv('Next action',p.next_action)}${p.analysis_status?`<div class="notice">Analysis: ${esc(human(p.analysis_status))}</div>`:''}<div class="form-actions"><button class="button secondary" id="edit-contact">Edit contact</button>${analyze?`<button class="button" id="analyze" ${['running','queued'].includes(p.analysis_status)?'disabled':''}>${p.analysis_status==='failed'?'Retry analysis':'Run research & qualification'}</button>`:''}</div></div>`)}
 ${panel('Research summary',research)}
 ${panel('Relationship timeline',p.timeline.length?`<div class="panel-body">${p.timeline.map(t=>`<div class="timeline-row"><small>${date(t.at,true)}</small>${t.href?`<a class="text-link" href="${esc(t.href)}">${esc(t.title)} ↗</a>`:`<strong>${esc(t.title)}</strong>`} <span>${badge(t.status)}</span></div>`).join('')}</div>`:empty('No activity yet','Research, communication and relationship events will appear as they happen.'),link(`outreach?restaurant=${p.id}`,'Open outreach'))}
 </div><div>${panel('Communication',`<div class="panel-body"><div class="kv"><span>Response</span>${badge(p.response)}</div>${kv('Follow-ups sent',p.followup_attempts)}${kv('Last contact',date(p.last_contact))}${kv('Last response',date(p.last_response))}${kv('Next follow-up',date(p.next_contact))}<a class="button secondary" style="width:100%;margin-top:15px" href="#/outreach?restaurant=${p.id}">${p.can_start?'Prepare initial outreach':'Open outreach workspace'}</a></div>`)}
 ${panel('Strategy',`<div class="panel-body">${kv('Request',human(p.strategy_request_status||'Not started'))}${kv('Saved plan',p.strategy_id?'Available':'Not available')}${kv('Delivery',p.strategy_delivered?'Provider accepted':'Not confirmed')}${link(`strategies?restaurant=${p.id}`,'View strategy workspace')}</div>`)}
 ${panel('30-day free trial',`<div class="panel-body">${trial(p)}</div>`)}
 ${panel('Latest feedback',`<div class="panel-body">${p.latest_feedback?`<p>${esc(p.latest_feedback.message)}</p><small>${date(p.latest_feedback.date)}</small>`:'<p>No feedback received yet.</p>'}<div style="margin-top:15px">${link(`feedback?restaurant=${p.id}`,'Open feedback')}</div></div>`)}
 ${p.relevant_events.length?panel('Relevant occasions',`<div class="panel-body">${p.relevant_events.map(x=>`<p>${esc(x)}</p>`).join('')}<small>Context selected for previous outreach.</small></div>`):''}</div></div>`,
 bind(){const btn=document.querySelector('#analyze');if(btn)btn.onclick=()=>busy(btn,async()=>{await post(`/api/restaurants/${p.id}/analyze`);toast('Analysis started. Refresh to see its progress.');window.dispatchEvent(new Event('agency-refresh'));});
 document.querySelector('#edit-contact').onclick=()=>{const d=modal(`<div class="modal-head"><h2>Contact details</h2><button class="icon-button" data-close aria-label="Close">×</button></div><form id="edit-form"><label for="contact-email">Email</label><input id="contact-email" type="email" name="email" value="${esc(p.email||'')}"><label for="contact-location" style="margin-top:15px">Location</label><input id="contact-location" name="location" value="${esc(p.location||'')}"><div class="form-actions"><button class="button" type="submit">Save details</button></div></form>`);d.querySelector('form').onsubmit=e=>{e.preventDefault();busy(e.submitter,async()=>{const values=Object.fromEntries(new FormData(e.target));for(const key of ['email','location'])if(!values[key])values[key]=null;await api(`/api/restaurants/${p.id}`,{method:'PATCH',body:JSON.stringify(values)});d.close();toast('Contact details updated.');window.dispatchEvent(new Event('agency-refresh'));});};};}};
}
